site_name: Blueprint Assist
theme:
  name: material
  palette:
      scheme: slate
      primary: default
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  font:
    text: Open Sans
    code: JetBrains Mono
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - attr_list
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: False
      video_autoplay: True
      video_loop: True
      css_style:
        width: "auto" 